#!/bin/bash

shopt -s dotglob
shopt -s nullglob



generatecatfile(){
	rm "$1"
	touch "$1"
	local filename="$1"
	echo '#!/bin/bash' >> "$filename"
	echo 'shopt -s dotglob' >> "$filename"
	echo 'shopt -s nullglob' >> "$filename"
	echo 'logtimedir_remote=/home/dungnt/StoreProj/logtime' >> "$filename"
	echo 'logtimefile=logtimefile.txt' >> "$filename"
	echo 'verify_logged() {' >> "$filename"
	echo '	local kq' >> "$filename"
	echo '	local cmd' >> "$filename"
	echo '	local value' >> "$filename"
	echo '	local curtime' >> "$filename"
	echo '	local delaytime' >> "$filename"
	echo '	kq=1' >> "$filename"
	echo '	value=$(tail -n 1 "$logtimedir_remote"/"$logtimefile")' >> "$filename"
	echo '	cmd=$?' >> "$filename"
	echo '	if [ "$cmd" -eq 0 ] ; then' >> "$filename"
	echo '		if [ "$value" ] ; then' >> "$filename"
	echo '			curtime=$(($(date +%s%N)/1000000))' >> "$filename"
	echo '			echo "$value"' >> "$filename"
	echo '			delaytime=$(( ( $curtime - $value ) / 60000 ))' >> "$filename"
	echo '			echo "$delaytime"' >> "$filename"
	echo '			if [ "$delaytime" -gt 6 ] ; then' >> "$filename"
	echo '				kq=0' >> "$filename"
	echo '			else' >> "$filename"
	echo '				kq=255' >> "$filename"
	echo '			fi' >> "$filename"
	echo '		fi' >> "$filename"
	echo '	fi' >> "$filename"
	echo '	return "$kq"' >> "$filename"
	echo '}' >> "$filename"
	echo 'appendfileinremotefunc(){' >> "$filename"
	echo '	local filename="$1"' >> "$filename"
	echo '	local tempfilename="$2"' >> "$filename"
	echo '	local newfilename="$3"' >> "$filename"
	echo '	local truncsize="$4"' >> "$filename"
	echo '	local tempfilesize="$5"' >> "$filename"
	echo '	local cmd1' >> "$filename"
	echo '	local cmd2' >> "$filename"
	echo '	local result' >> "$filename"
	echo '	local numcount' >> "$filename"
	echo '	local numcountmodulo' >> "$filename"
	echo '	local skipsize=0' >> "$filename"
	echo '	mv "$filename" "$newfilename"' >> "$filename"
	echo '	truncate -s "$truncsize" "$newfilename"' >> "$filename"
	echo '	numcount=$(( $tempfilesize/(500*1000*1000) ))' >> "$filename"
	echo '	numcountmodulo=$(( $tempfilesize%(500*1000*1000) ))' >> "$filename"
	echo '	if [ "$numcountmodulo" -ne 0 ] ; then' >> "$filename"
	echo '		numcount=$(( $numcount + 1 ))' >> "$filename"
	echo '	fi' >> "$filename"
	echo '	while [ "$skipsize" -lt "$numcount" ] ; do' >> "$filename"
	echo '		while true; do	' >> "$filename"
	echo '			verify_logged' >> "$filename"
	echo '			cmd1=$?' >> "$filename"
	echo '			echo "$cmd1"' >> "$filename"
	echo '			result=$(netstat -atn | grep ":22 " | grep "ESTABLISHED" | wc -l)' >> "$filename"
	echo '			cmd2=$?' >> "$filename"
	echo '			echo "$cmd2"" ""$result"' >> "$filename"
	echo '			if [ "$cmd1" -eq 0 ] && [ "$cmd2" -eq 0 ] && [ "$result" -lt 2 ] ; then' >> "$filename"
	echo '				break' >> "$filename"
	echo '			else' >> "$filename"
	echo '				echo "sleep 15s"' >> "$filename"
	echo '				sleep 15			' >> "$filename"
	echo '			fi	' >> "$filename"
	echo '		done' >> "$filename"
	echo '		dd if="$tempfilename" bs="500MB" count=1 skip="$skipsize" >> "$newfilename"' >> "$filename"
	echo '		skipsize=$(( $skipsize + 1 ))' >> "$filename"
	echo '	done' >> "$filename"
	echo '	rm "$tempfilename"' >> "$filename"
	echo '}' >> "$filename"
	echo 'appendfileinremotefunc "filename" "tempfilename" "newfilename" 1 13' >> "$filename"
}

generatecatfile test6.sh
